services:
  - name: zveno-server
    type: web
    region: frankfurt
    env: docker
    dockerfilePath: zveno/server/Dockerfile
    dockerCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zveno-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://your-client.vercel.app
      - key: ANNOUNCED_IP
        value: 0.0.0.0
    autoDeploy: true
    healthCheckPath: /

  - name: zveno-db
    type: pserv
    region: frankfurt
    postgresMajorVersion: "15"
    postgresVersion: "latest"
    plan: free

databases:
  - name: zveno-db
    region: frankfurt
    plan: free
